package main

import (
	"backend/config"
	"backend/middleware"
	"backend/models"
	"backend/routers"
	"fmt"

	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

var r = gin.New()

const (
	separator      = "---------------"
	shortSeparator = "----------"
)

func init() {
	fmt.Println(separator, " init system start", separator)

	fmt.Println(shortSeparator, " setting init start", shortSeparator)
	config.SetUp()
	fmt.Println(shortSeparator, " setting init end ", shortSeparator)

	fmt.Println(shortSeparator, " models init start", shortSeparator)
	models.SetUp()
	fmt.Println(shortSeparator, " models init end ", shortSeparator)

	fmt.Println(shortSeparator, " middlewares init start", shortSeparator)
	middleware.SetUp(r)
	fmt.Println(shortSeparator, " middlewares init end ", shortSeparator)

	fmt.Println(shortSeparator, " routers init start", shortSeparator)
	routers.SetUp(r)
	fmt.Println(shortSeparator, " routers init end ", shortSeparator)

	fmt.Println(separator, " init system end ", separator)
}

func main() {
	url := ginSwagger.URL(fmt.Sprintf("http://localhost:%s/swagger/doc.json", config.AppSetting.Port)) // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	r.Run(fmt.Sprintf(":%s", config.AppSetting.Port))
}
