basePath: /v1
host: 127.0.0.1:8050
info:
  contact:
    email: contact email
    name: contact name
    url: contact url
  description: 个description
  license:
    name: license name
    url: liscense url
  title: title
  version: 0.0.1
paths:
  /tag/all:
    get:
      consumes:
      - multipart/form-data
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
        "400":
          description: '{"error"}'
          schema:
            type: string
      summary: 获取所有的Tag
      tags:
      - GetAllTags
schemes:
- http
swagger: "2.0"
tags:
- description: tag description
  externalDocs:
    description: doc description
    url: doc url
  name: tag
