basePath: /v1
host: 127.0.0.1:8050
info:
  contact:
    email: hellozfy1996@gmail.com
  description: 个人博客 go学习
  license: {}
  title: 个人博客 API
  version: 0.0.1
paths:
  /tag/all:
    get:
      consumes:
      - multipart/form-data
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
        "400":
          description: '{"error"}'
          schema:
            type: string
      summary: 获取所有的Tag
      tags:
      - GetAllTags
swagger: "2.0"
