basePath: /v1
definitions:
  dto.CreateCategoryDTO:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
  dto.CreateTagDTO:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
  dto.UpdateCategoryDTO:
    properties:
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    required:
    - id
    type: object
  dto.UpdateTagDTO:
    properties:
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    required:
    - id
    type: object
  models.Article:
    properties:
      body:
        type: string
      categoryId:
        type: integer
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: integer
      subTitle:
        type: string
      tags:
        items:
          $ref: '#/definitions/models.Tag'
        type: array
      title:
        type: string
      updateAt:
        type: string
      userId:
        type: integer
    type: object
  models.Category:
    properties:
      articles:
        items:
          $ref: '#/definitions/models.Article'
        type: array
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updateAt:
        type: string
    type: object
  models.Tag:
    properties:
      articles:
        items:
          $ref: '#/definitions/models.Article'
        type: array
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updateAt:
        type: string
    type: object
host: 127.0.0.1:8050
info:
  contact:
    email: contact email
    name: contact name
    url: contact url
  description: description
  license:
    name: license name
    url: liscense url
  title: title
  version: 0.0.1
paths:
  /category/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: row
        in: body
        name: row
        schema:
          $ref: '#/definitions/dto.CreateCategoryDTO'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 创建类型
      tags:
      - category
  /category/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 获取所有的类型
      tags:
      - category
  /category/count:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 获取类型总数
      tags:
      - category
  /category/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"msg":"操作成功", "data":{}}'
          schema:
            $ref: '#/definitions/models.Category'
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 根据id删除类型
      tags:
      - category
  /category/id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"msg":"操作成功", "data":{}}'
          schema:
            $ref: '#/definitions/models.Category'
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 根据id获取类型
      tags:
      - category
  /category/update:
    put:
      consumes:
      - application/json
      parameters:
      - description: row
        in: body
        name: row
        schema:
          $ref: '#/definitions/dto.UpdateCategoryDTO'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 编辑类型
      tags:
      - category
  /tag/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: row
        in: body
        name: row
        schema:
          $ref: '#/definitions/dto.CreateTagDTO'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 创建标签
      tags:
      - tag
  /tag/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 获取所有的标签
      tags:
      - tag
  /tag/count:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 获取标签总数
      tags:
      - tag
  /tag/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"msg":"操作成功", "data":{}}'
          schema:
            $ref: '#/definitions/models.Tag'
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 根据id删除标签
      tags:
      - tag
  /tag/id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"msg":"操作成功", "data":{}}'
          schema:
            $ref: '#/definitions/models.Tag'
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 根据id获取标签
      tags:
      - tag
  /tag/update:
    put:
      consumes:
      - application/json
      parameters:
      - description: row
        in: body
        name: row
        schema:
          $ref: '#/definitions/dto.UpdateTagDTO'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
        "500":
          description: '{"code":1001,"msg":"查询出错", "data":null}'
          schema:
            type: string
      summary: 编辑标签
      tags:
      - tag
schemes:
- http
swagger: "2.0"
